/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, lazyFn } from '@tanstack/react-router'

// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardBackendsImport } from './routes/dashboard/backends'
import { Route as DashboardFiltersImport } from './routes/dashboard/filters'
import { Route as DashboardAnalyticsImport } from './routes/dashboard/analytics'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'

// Create/Update Routes
const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBackendsRoute = DashboardBackendsImport.update({
  path: '/backends',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFiltersRoute = DashboardFiltersImport.update({
  path: '/filters',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAnalyticsRoute = DashboardAnalyticsImport.update({
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

// Create and export the route tree
export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashboardRoute: DashboardRoute.addChildren({
    DashboardIndexRoute,
    DashboardBackendsRoute,
    DashboardFiltersRoute,
    DashboardAnalyticsRoute,
    DashboardSettingsRoute,
  }),
  AuthLoginRoute,
  AuthRegisterRoute,
})
