/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DashboardSetupRouteImport } from './routes/dashboard/setup'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardIpLookupRouteImport } from './routes/dashboard/ip-lookup'
import { Route as DashboardFiltersRouteImport } from './routes/dashboard/filters'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardBackendsRouteImport } from './routes/dashboard/backends'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminMetricsRouteImport } from './routes/admin/metrics'
import { Route as AdminBlacklistsRouteImport } from './routes/admin/blacklists'
import { Route as AdminBackendsRouteImport } from './routes/admin/backends'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminAttacksRouteImport } from './routes/admin/attacks'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIpLookupRoute = DashboardIpLookupRouteImport.update({
  id: '/ip-lookup',
  path: '/ip-lookup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFiltersRoute = DashboardFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackendsRoute = DashboardBackendsRouteImport.update({
  id: '/backends',
  path: '/backends',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/admin/metrics',
  path: '/admin/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlacklistsRoute = AdminBlacklistsRouteImport.update({
  id: '/admin/blacklists',
  path: '/admin/blacklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackendsRoute = AdminBackendsRouteImport.update({
  id: '/admin/backends',
  path: '/admin/backends',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttacksRoute = AdminAttacksRouteImport.update({
  id: '/admin/attacks',
  path: '/admin/attacks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/attacks': typeof AdminAttacksRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/backends': typeof AdminBackendsRoute
  '/admin/blacklists': typeof AdminBlacklistsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backends': typeof DashboardBackendsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/filters': typeof DashboardFiltersRoute
  '/dashboard/ip-lookup': typeof DashboardIpLookupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/docs/$': typeof DocsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/attacks': typeof AdminAttacksRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/backends': typeof AdminBackendsRoute
  '/admin/blacklists': typeof AdminBlacklistsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backends': typeof DashboardBackendsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/filters': typeof DashboardFiltersRoute
  '/dashboard/ip-lookup': typeof DashboardIpLookupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/docs/$': typeof DocsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/attacks': typeof AdminAttacksRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/backends': typeof AdminBackendsRoute
  '/admin/blacklists': typeof AdminBlacklistsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backends': typeof DashboardBackendsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/filters': typeof DashboardFiltersRoute
  '/dashboard/ip-lookup': typeof DashboardIpLookupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/docs/$': typeof DocsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/admin/attacks'
    | '/admin/audit-log'
    | '/admin/backends'
    | '/admin/blacklists'
    | '/admin/metrics'
    | '/admin/organizations'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/$authView'
    | '/dashboard/analytics'
    | '/dashboard/backends'
    | '/dashboard/billing'
    | '/dashboard/filters'
    | '/dashboard/ip-lookup'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/docs/$'
    | '/admin'
    | '/dashboard/'
    | '/docs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/attacks'
    | '/admin/audit-log'
    | '/admin/backends'
    | '/admin/blacklists'
    | '/admin/metrics'
    | '/admin/organizations'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/$authView'
    | '/dashboard/analytics'
    | '/dashboard/backends'
    | '/dashboard/billing'
    | '/dashboard/filters'
    | '/dashboard/ip-lookup'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/docs/$'
    | '/admin'
    | '/dashboard'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/admin/attacks'
    | '/admin/audit-log'
    | '/admin/backends'
    | '/admin/blacklists'
    | '/admin/metrics'
    | '/admin/organizations'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/$authView'
    | '/dashboard/analytics'
    | '/dashboard/backends'
    | '/dashboard/billing'
    | '/dashboard/filters'
    | '/dashboard/ip-lookup'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/docs/$'
    | '/admin/'
    | '/dashboard/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminAttacksRoute: typeof AdminAttacksRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBackendsRoute: typeof AdminBackendsRoute
  AdminBlacklistsRoute: typeof AdminBlacklistsRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  DocsSplatRoute: typeof DocsSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ip-lookup': {
      id: '/dashboard/ip-lookup'
      path: '/ip-lookup'
      fullPath: '/dashboard/ip-lookup'
      preLoaderRoute: typeof DashboardIpLookupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/filters': {
      id: '/dashboard/filters'
      path: '/filters'
      fullPath: '/dashboard/filters'
      preLoaderRoute: typeof DashboardFiltersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/backends': {
      id: '/dashboard/backends'
      path: '/backends'
      fullPath: '/dashboard/backends'
      preLoaderRoute: typeof DashboardBackendsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/admin/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blacklists': {
      id: '/admin/blacklists'
      path: '/admin/blacklists'
      fullPath: '/admin/blacklists'
      preLoaderRoute: typeof AdminBlacklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backends': {
      id: '/admin/backends'
      path: '/admin/backends'
      fullPath: '/admin/backends'
      preLoaderRoute: typeof AdminBackendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attacks': {
      id: '/admin/attacks'
      path: '/admin/attacks'
      fullPath: '/admin/attacks'
      preLoaderRoute: typeof AdminAttacksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBackendsRoute: typeof DashboardBackendsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardFiltersRoute: typeof DashboardFiltersRoute
  DashboardIpLookupRoute: typeof DashboardIpLookupRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBackendsRoute: DashboardBackendsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardFiltersRoute: DashboardFiltersRoute,
  DashboardIpLookupRoute: DashboardIpLookupRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminAttacksRoute: AdminAttacksRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBackendsRoute: AdminBackendsRoute,
  AdminBlacklistsRoute: AdminBlacklistsRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  DocsSplatRoute: DocsSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
